# PyTorch Fundamentals

# 1. Matrices

## 1.1 Creating Matrices

In [1]:
import numpy as np

In [2]:
# Creating a 2x2 array
arr = [[1,2], [3,4]]
print (arr)

[[1, 2], [3, 4]]


In [3]:
# converto To NumPy
np.array(arr)

array([[1, 2],
       [3, 4]])

In [4]:
import torch

In [6]:
# convert to Pytroch Tensor
torch.Tensor(arr)


 1  2
 3  4
[torch.FloatTensor of size 2x2]

## 1.2 Create Matrices with Default Values

In [7]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [8]:
torch.ones((2, 2))


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [9]:
np.random.rand(2, 2)

array([[0.96299203, 0.72242878],
       [0.60032453, 0.42480616]])

In [10]:
torch.rand(2, 2)


 0.4404  0.5194
 0.2116  0.3532
[torch.FloatTensor of size 2x2]

## 1.3 Seeds for Reproducibility

In [16]:
# seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [17]:
# seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [14]:
# No seed
np.random.rand(2, 2)

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [15]:
# No seed
np.random.rand(2, 2)

array([[0.96366276, 0.38344152],
       [0.79172504, 0.52889492]])

In [18]:
# Torch Seed
torch.manual_seed(0)
torch.rand(2,2)


 0.4963  0.7682
 0.0885  0.1320
[torch.FloatTensor of size 2x2]

In [19]:
# Torch No Seed
torch.rand(2,2)


 0.3074  0.6341
 0.4901  0.8964
[torch.FloatTensor of size 2x2]

In [20]:
# Torch No Seed
torch.rand(2,2)


 0.4556  0.6323
 0.3489  0.4017
[torch.FloatTensor of size 2x2]

### Seed for GPU is different for now...

In [21]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

In [22]:
torch.cuda.is_available()

False

## 1.3 Numpy and Torch Bridge

### NumPy to Torch

In [23]:
# Numpy Array
np_array = np.ones((2,2))

In [25]:
print(np_array)

[[1. 1.]
 [1. 1.]]


In [26]:
print (type(np_array))

<class 'numpy.ndarray'>


In [27]:
# Convert to Torch Tensor
torch_tensor = torch.from_numpy(np_array)

In [28]:
print (torch_tensor)


 1  1
 1  1
[torch.DoubleTensor of size 2x2]



In [29]:
print (type(torch_tensor))

<class 'torch.DoubleTensor'>


In [30]:
# Data types matter: intentional error
np_array_new = np.ones((2, 2), dtype=np.int8)
torch.from_numpy(np_array_new)

RuntimeError: can't convert a given np.ndarray to a tensor - it has an invalid type. The only supported types are: double, float, int64, int32, and uint8.

### The conversion supports:

1. double
2. float
3. int64, int32, uint8

In [32]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.int64)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.LongTensor of size 2x2]

In [33]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.int32)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.IntTensor of size 2x2]

In [35]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.uint8)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.ByteTensor of size 2x2]

In [36]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.float64)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.DoubleTensor of size 2x2]

In [37]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.float32)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [38]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.double)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.DoubleTensor of size 2x2]

### summary
These things don't matter much now. But later when you see error messages that require these particular tensor types, refer to this guide!

| NumPy Array Type | Torch Tensor Type|
| -----------------|:----------------:|
| int64      | LongTensor|
| int32      | IntengerTensor     |
| uint8 | Byte Tensor|
| float64 | DobuleTensor    |
| float32 | FloatTensor|
| double | DoubleTensor |

### Torcy to Numpy

In [39]:
torch_tensor = torch.ones(2, 2)

In [40]:
type(torch_tensor)

torch.FloatTensor

In [41]:
torch_to_numpy = torch_tensor.numpy()

In [42]:
type(torch_to_numpy)

numpy.ndarray

## 1.4 Tensors on CPU vs GPU

In [43]:
# CPU
tensor_cpu = torch.ones(2, 2)

In [44]:
# CPU to GPU
if torch.cuda.is_available():
    tensor_cpu.cuda() # .cuda() 를 통해서 gpu로

In [ ]:
# GPU to CPU
tensor_cpu.cpu()

## 1.5 Tensor Operations

### Resizing Tensor

In [45]:
a = torch.ones(2, 2)
print (a)


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [46]:
print (a.size())

torch.Size([2, 2])


In [47]:
a.view(4)


 1
 1
 1
 1
[torch.FloatTensor of size 4]

In [48]:
a.view(4)


 1
 1
 1
 1
[torch.FloatTensor of size 4]

### Element-wise Addition

In [49]:
a = torch.ones(2, 2)
print (a)


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [50]:
b = torch.ones(2, 2)
print (b)


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [51]:
# Element-wise addition
c = a + b
print (c)


 2  2
 2  2
[torch.FloatTensor of size 2x2]



In [52]:
# Element-wise addition
c = torch.add(a, b)
print (c)


 2  2
 2  2
[torch.FloatTensor of size 2x2]



In [54]:
# In-place addition
print ('Old c tensor')
print (c)

c.add_(a)

print ('-'*60)
print ('New c tensor')
print (c)

Old c tensor

 2  2
 2  2
[torch.FloatTensor of size 2x2]

------------------------------------------------------------
New c tensor

 3  3
 3  3
[torch.FloatTensor of size 2x2]



### Element-wise Subtraction

In [55]:
print(a)
print(b)


 1  1
 1  1
[torch.FloatTensor of size 2x2]


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [56]:
a - b


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [57]:
# Not in-place
print (a.sub(b))
print (a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [58]:
# Inplace
print (a.sub_(b))
print (a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]


 0  0
 0  0
[torch.FloatTensor of size 2x2]



### Element-Wise Multiplication

In [59]:
a = torch.ones(2, 2)
print (a)
b = torch.zeros(2, 2)
print (b)


 1  1
 1  1
[torch.FloatTensor of size 2x2]


 0  0
 0  0
[torch.FloatTensor of size 2x2]



In [60]:
a * b


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [61]:
# Not in-place
print (torch.mul(a, b))
print (a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [62]:
# In-place
print (a.mul_(b))
print (a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]


 0  0
 0  0
[torch.FloatTensor of size 2x2]



### Element-Wise Division

In [63]:
a = torch.ones(2, 2)
b = torch.zeros(2, 2)

In [64]:
b / a


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [65]:
torch.div(b, a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [66]:
# Inplace
b.div_(a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]

### Tensor Mean
- 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 = 55
- mean = 55/10 = 5.5

In [67]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.size()

torch.Size([10])

In [69]:
a.mean(dim=0)


 5.5000
[torch.FloatTensor of size 1]

In [70]:
a.mean(dim=1)

RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

In [71]:
a = torch.Tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])

In [75]:
print (a)


    1     2     3     4     5     6     7     8     9    10
    1     2     3     4     5     6     7     8     9    10
[torch.FloatTensor of size 2x10]



In [72]:
a.size()

torch.Size([2, 10])

In [76]:
a.mean(dim=0)


  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
[torch.FloatTensor of size 10]

In [77]:
a.mean(dim=1)


 5.5000
 5.5000
[torch.FloatTensor of size 2]

### Tensor Standard Deviation

In [78]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.std(dim=0)


 3.0277
[torch.FloatTensor of size 1]

## We've learnt to...

1. Create MAtrices
2. Create MAtrices with Default Initialization Values
 - Zeros
 - Ones
3. Initialize Seeds for Reproducibility on GPU and CPU
4. Convert Matrices: Numpy => Torch and Torch => CPU
5. Move Tensors: CPU => GPU and GPU => CPU
6. Run Important Tensor Operations
 - Element-wise addition, subtraction, multiplication and division
 - Resize
 - Calculate mean
 - Cacluate standard deviation