# 파이토치 기초

# 1. 행렬

## 1.1 행렬 만들기

matrix를 만들고 이를 torch.Tensor로 받아주기

In [1]:
import numpy as np
import torch

In [2]:
arr = [[1,2], [3,4]]
print (arr)

[[1, 2], [3, 4]]


In [3]:
np.array(arr)

array([[1, 2],
       [3, 4]])

In [4]:
import torch

In [5]:
torch.Tensor(arr)

tensor([[ 1.,  2.],
        [ 3.,  4.]])

## 1.2 기본 값으로 행렬 만들기

기본 값으로 행렬 만들기

In [6]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [7]:
torch.ones((2, 2))

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [8]:
np.random.randn(2, 2)

array([[ 0.64293728, -1.22045054],
       [ 0.18714808, -0.93115674]])

In [9]:
torch.rand(2, 2)

tensor([[ 0.6757,  0.2163],
        [ 0.6374,  0.3109]])

## 1.3 재성성을 위한 seed

In [10]:
# seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [11]:
# seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [12]:
# No seed
np.random.rand(2, 2)

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [13]:
# No seed
np.random.rand(2, 2)

array([[0.96366276, 0.38344152],
       [0.79172504, 0.52889492]])

In [14]:
# Torch seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[ 0.4963,  0.7682],
        [ 0.0885,  0.1320]])

In [15]:
# Torch Seed
torch.manual_seed(0)
torch.rand(2,2)

tensor([[ 0.4963,  0.7682],
        [ 0.0885,  0.1320]])

In [16]:
# Torch No seed
torch.rand(2, 2)

tensor([[ 0.3074,  0.6341],
        [ 0.4901,  0.8964]])

In [17]:
# Torch No seed
torch.rand(2, 2)

tensor([[ 0.4556,  0.6323],
        [ 0.3489,  0.4017]])

### GPU에 관한 Seed는 다르다...

In [18]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

In [19]:
torch.cuda.is_available()

False

## 1.3 Numpy와 Torch 사이의 변환

### NumPy 에서 Torch

In [20]:
# Numpy Array
np_array = np.ones((2, 2))

In [21]:
print (np_array)

[[1. 1.]
 [1. 1.]]


In [22]:
print (type(np_array))

<class 'numpy.ndarray'>


In [23]:
# Torch Tensor로 변환하기
torch_tensor = torch.from_numpy(np_array)

In [24]:
print (torch_tensor)

tensor([[ 1.,  1.],
        [ 1.,  1.]], dtype=torch.float64)


In [25]:
print (type(torch_tensor))

<class 'torch.Tensor'>


In [26]:
print (type(torch_tensor))

<class 'torch.Tensor'>


In [27]:
# Data types 이 중요하다: 의도적인 에러
np_array_new = np.ones((2, 2), dtype=np.int8)

In [28]:
torch.from_numpy(np_array_new)

TypeError: can't convert np.ndarray of type numpy.int8. The only supported types are: double, float, float16, int64, int32, and uint8.

### 변환을 지원하는 데이터타입:

1. double
2. float
3. int64, int32, uint8

In [29]:
# 데이터 타입이 중요하다
np_array_new = np.ones((2, 2), dtype=np.int64)
torch.from_numpy(np_array_new)

tensor([[ 1,  1],
        [ 1,  1]])

In [30]:
# 데이터 타입이 중요하다
np_array_new = np.ones((2, 2), dtype=np.int32)
torch.from_numpy(np_array_new)

tensor([[ 1,  1],
        [ 1,  1]], dtype=torch.int32)

In [31]:
# 데이터 타입이 중요하다
np_array_new = np.ones((2, 2), dtype=np.uint8)
torch.from_numpy(np_array_new)

tensor([[ 1,  1],
        [ 1,  1]], dtype=torch.uint8)

In [32]:
# 데이터 타입이 중요하다
np_array_new = np.ones((2, 2), dtype=np.uint8)
torch.from_numpy(np_array_new)

tensor([[ 1,  1],
        [ 1,  1]], dtype=torch.uint8)

In [33]:
# 데이터 타입이 중요하다
np_array_new = np.ones((2, 2), dtype=np.float64)
torch.from_numpy(np_array_new)

tensor([[ 1.,  1.],
        [ 1.,  1.]], dtype=torch.float64)

In [34]:
# 데이터 타입이 중요하다
np_array_new = np.ones((2, 2), dtype=np.float32)
torch.from_numpy(np_array_new)

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [35]:
# 데이터 타입이 중요하다.
np_array_new = np.ones((2, 2), dtype=np.double)
torch.from_numpy(np_array_new)

tensor([[ 1.,  1.],
        [ 1.,  1.]], dtype=torch.float64)

### summary
These things don't matter much now. But later when you see error messages that require these particular tensor types, refer to this guide!

### 요약
지금은 이러한 데이터 타입에 관한 것이 크게 중요하지 않다. 하지만 이후에 이러한 텐서 타입을 요구하는 에러 메시지를 본다면, 아래의 가이드를 참고하자!

| NumPy Array Type | Torch Tensor Type|
| -----------------|:----------------:|
| int64      | LongTensor|
| int32      | IntengerTensor     |
| uint8 | Byte Tensor|
| float64 | DobuleTensor    |
| float32 | FloatTensor|
| double | DoubleTensor |

### Torch에서 NumPy로

In [36]:
torch_tensor = torch.ones(2, 2)

In [37]:
type(torch_tensor)

torch.Tensor

In [38]:
torch_to_numpy = torch_tensor.numpy()

In [39]:
type(torch_to_numpy)

numpy.ndarray

In [40]:
torch_to_numpy.dtype

dtype('float32')

## 1.4 CPU와 GPU 에서의 텐서들

In [41]:
# CPU
tensor_cpu = torch.ones(2, 2)

In [42]:
# CPU to GPU
# .cuda() 만 붙여주면 된다.
if torch.cuda.is_available():
    tensor_cpu.cuda()

In [43]:
# GPU에서 CPU
# .cpu() 만 붙여주면 된다.
tensor_cpu.cpu()

tensor([[ 1.,  1.],
        [ 1.,  1.]])

## 1.5 텐서 연산들

### 텐서 사이즈 조절하기

In [44]:
a = torch.ones(2, 2)
print (a)

tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [45]:
print (a.size())

torch.Size([2, 2])


In [65]:
# numpy의 reshape와 비슷하다
a.view(4)

tensor([ 1.,  1.,  1.,  1.])

In [66]:
b = a.view(4)
b.size()

torch.Size([4])

### 요소별 덧셈

In [67]:
a = torch.ones(2, 2)
print (a)

tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [68]:
b = torch.ones(2, 2)
print (b)

tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [76]:
# 요소별 덧셈
c = a + b
c

tensor([[ 2.,  2.],
        [ 2.,  2.]])

In [77]:
print ('Old c Tensor')
print (c)

Old c Tensor
tensor([[ 2.,  2.],
        [ 2.,  2.]])


In [78]:
# In-Place 덧셈
c.add_(a)

tensor([[ 3.,  3.],
        [ 3.,  3.]])

In [80]:
# c의 값이 inplace로 늘었다.
print (c)

tensor([[ 3.,  3.],
        [ 3.,  3.]])


### 요소별 뺄셈

In [81]:
print (a)

tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [82]:
print (b)

tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [83]:
a - b

tensor([[ 0.,  0.],
        [ 0.,  0.]])

In [84]:
# in-place 아닌 경우
print (a)
print (a.sub(b))
print (a)

tensor([[ 1.,  1.],
        [ 1.,  1.]])
tensor([[ 0.,  0.],
        [ 0.,  0.]])
tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [85]:
# inplace 
print (a.sub_(b))
print (a)

tensor([[ 0.,  0.],
        [ 0.,  0.]])
tensor([[ 0.,  0.],
        [ 0.,  0.]])


### 요소별 곱셈

In [86]:
a = torch.ones(2, 2)
b = torch.zeros(2, 2)

In [88]:
print (a)
print (b)

tensor([[ 1.,  1.],
        [ 1.,  1.]])
tensor([[ 0.,  0.],
        [ 0.,  0.]])


In [89]:
a * b

tensor([[ 0.,  0.],
        [ 0.,  0.]])

In [90]:
# in-place 아닌 경우
print (torch.mul(a, b))
print (a)

tensor([[ 0.,  0.],
        [ 0.,  0.]])
tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [91]:
# in-place
print (a.mul_(b))
print (a)

tensor([[ 0.,  0.],
        [ 0.,  0.]])
tensor([[ 0.,  0.],
        [ 0.,  0.]])


### 요소별 나눗셈

In [95]:
1 / 0

ZeroDivisionError: division by zero

In [96]:
0 / 1

0.0

In [94]:
a = torch.ones(2, 2)
b = torch.zeros(2, 2)

In [97]:
b / a

tensor([[ 0.,  0.],
        [ 0.,  0.]])

In [98]:
torch.div(b, a)

tensor([[ 0.,  0.],
        [ 0.,  0.]])

In [99]:
# inplace
b.div_(a)
b

tensor([[ 0.,  0.],
        [ 0.,  0.]])

### 텐서 평균
- 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 = 55
- mean = 55/10 = 5.5

In [100]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [101]:
a.size()

torch.Size([10])

In [104]:
a.mean(dim=0)

tensor(5.5000)

In [111]:
a.mean(dim=0)

tensor(5.5000)

In [70]:
a.mean(dim=1)

RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

In [113]:
a = torch.Tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])

In [114]:
a

tensor([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
        [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.]])

In [115]:
a.size()

torch.Size([2, 10])

In [116]:
a.mean(dim=0)

tensor([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [122]:
a.mean(dim=1)

tensor([ 5.5000,  5.5000])

### 텐서 표준편차

In [123]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.std(dim=0)

tensor(3.0277)

## 우리가 배운것은 ...

1. 행렬 생성
2. 기본 초기값을 갖고 행렬 생성
 - Zeros
 - Ones
3. 재생성을 위한 Seed 초기값 설정
4. 행렬 변환: NumPy => Torch, Torch => NumPy
5. 행렬 이동시키기: CPU > GPU, GPU => CPU
6. 중요한 텐서 연산들 실행시키기
 - 요소별 덧셈, 뺄셈, 곱, 나눗셈
 - 리사이즈(view)
 - 평균값 계산
 - 표준편차 계산