# 파이토치 기초

# 2. 변수와 그라디언트

## 2.1 변수
- 변수는 텐서를 덧씌울 수 있다.
- 그라디언트들이 쌓이게 허용해 준다.

In [2]:
import torch
from torch.autograd import Variable

In [3]:
a = Variable(torch.ones(2, 2), requires_grad = True)
a 

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [4]:
# 변수가 아닌 경우
torch.ones(2, 2)

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [5]:
# 텐서와 유사하게 동작한다.
b = Variable(torch.ones(2, 2), requires_grad = True)

In [7]:
print (a + b)

tensor([[ 2.,  2.],
        [ 2.,  2.]])


In [8]:
print (torch.add(a, b))

tensor([[ 2.,  2.],
        [ 2.,  2.]])


In [9]:
print (a * b)
print (torch.mul(a, b))

tensor([[ 1.,  1.],
        [ 1.,  1.]])
tensor([[ 1.,  1.],
        [ 1.,  1.]])


## 2.2 그라디언트

### requires_grad가 뜻하는 바는 무엇일까?

- 변수들에 관해 그라디언트 계산이 가능하도록 해 주는 옵션이다.

$$y_i = 5(x_i + 1)^2$$

In [49]:
x = Variable(torch.ones(2), requires_grad=True)
x

tensor([ 1.,  1.])

$$y_i|_{x_{i}=1} = 5(1 + 1)^2 = 5(2)^2 = 5(4) = 20$$ 

In [50]:
y = 5 * (x + 1) ** 2
y

tensor([ 20.,  20.])

### Backward 는 오직 스칼라(즉, 1차원 텐서) 혹은 변수들에 대한 그라디언트에서 호출되어야 한다.

- y를 스칼라로 줄인다... (평균을 해 준다)

$$o = \frac{1}{2}\sum_{i}y_i$$

In [51]:
o = (1/2) * torch.sum(y)
o

tensor(20.)

<center>**Recap y equation:** $y_i = 5(x_i + 1)^2$</center><br/>
<center>**Recap o equation:** $o = \frac{1}{2}\sum_{i}y_i$</center><br/>
<center>**Substitute y into o equation:** $o = \frac{1}{2}\sum_{i}5(x_i + 1)^2$</center><br/>
$$\frac{\partial{o}}{\partial{x_i}} = \frac{1}{2}[10(x_i + 1)]$$<br/>
$$\frac{\partial{o}}{\partial{x_i}}|_{x_{i} = 1} = \frac{1}{2}[10(1 + 1)] = \frac{10}{2}(2) = 10$$




In [16]:
o.backward() # 이때 gradient 계산한다

In [17]:
x.grad # 계산한 gradient는 이렇게 확인한다.

tensor([ 10.,  10.])

In [52]:
# backward in detail
o.backward(torch.FloatTensor([1.0, 1.0]))
x.grad

tensor([ 10.,  10.])

<hr/>

## 요약

- 변수
    - 그라디언트 축적을 위해 텐서를 감싸준다.
- 그라디언트
    - 원래의 식을 정의한다.
    - 식을 x값들로 대체한다.
    - 평균을 통해 스칼라 아웃풋 o 로 줄여준다.
    
    - Define origianl equation
    - Substitute equation with x values
    - Reduce to scalar output o through mean
    - Calculate gradients with o.backward()
    - Then access gradients of the x variable through x.grad

- Variable
    - Wraps a tensor for gradient accuulation
- Gradients
    - Define origianl equation
    - Substitute equation with x values
    - Reduce to scalar output o through mean
    - Calculate gradients with o.backward()
    - Then access gradients of the x variable through x.grad